const SET_FREQUENCY = "SET_FREQUENCY";

export const SET_FREQUENCYDAY = "SET_FREQUENCYDAY",
  SET_PAYMENTTIME = "SET_PAYMENTTIME",
  SET_PAYMENTQUANTITY = "SET_PAYMENTQUANTITY",
  SET_PAYMENTQUANTITY_TIMES = "SET_PAYMENTQUANTITY_TIMES",
  SET_PAYMENTQUANTITY_TILL = "SET_PAYMENTQUANTITY_TILL";

export default SET_FREQUENCY;
